

arvore: arvore.c operations_arvore.c
	gcc -o arvore -g arvore.c operations_arvore.c -I.  # -Wall -Wextra -Werror -std=c99 -pedantic -O2

matriz: matrix.c operations_mat.c
	gcc -o matrix -g matrix.c operations_mat.c -I.  # -Wall -Wextra -Werror -std=c99 -pedantic -O2

all : arvore matrix